-- SQL Script to set up the University Permit System Database
-- Create the Database
CREATE DATABASE IF NOT EXISTS university_paws;
USE university_paws;

-- Create Users Table
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    student_id VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM('student', 'admin') DEFAULT 'student',
    grade_level ENUM('Senior High', 'College') NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create Permits Table
CREATE TABLE IF NOT EXISTS permits (
    id INT AUTO_INCREMENT PRIMARY KEY,
    student_id VARCHAR(50) NOT NULL,
    permit_type VARCHAR(100) NOT NULL,
    event_date DATE NOT NULL,
    purpose TEXT NOT NULL,
    status ENUM('Pending', 'Approved', 'Rejected') DEFAULT 'Pending',
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (student_id) REFERENCES users(student_id) ON DELETE CASCADE
);

-- Create Permit Files Table
CREATE TABLE IF NOT EXISTS permit_files (
    id INT AUTO_INCREMENT PRIMARY KEY,
    permit_id INT NOT NULL,
    file_type VARCHAR(50) NOT NULL, -- e.g., 'request_form', 'student_id', 'endorsement'
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(255) NOT NULL,
    FOREIGN KEY (permit_id) REFERENCES permits(id) ON DELETE CASCADE
);

-- Insert Pre-existing Admin Account
-- User ID: Admin
-- Password: adminpass
-- (The password below is securely hashed using Bcrypt)
INSERT INTO users (student_id, password, role) VALUES 
('Admin', '$2y$10$fN8u7fN8u7fN8u7fN8u7fO.vO.vO.vO.vO.vO.vO.vO.vO.vO.vO.', 'admin');
-- NOTE: In a production environment, you should use a unique hash generated by password_hash().

